name: Déploiement GitHub Pages
 
on:
  push:
    branches:
      - main # selon le nom de ta branche principale
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
 
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Le dossier racine contient index.html
